"""initial schema

Revision ID: 453af1235dc8
Revises: 
Create Date: 2026-09-29 09:03:35.713376

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453af1235dc8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_imports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=False),
    sa.Column('vintage', sa.String(length=16), nullable=False),
    sa.Column('release_label', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('variables_json', sa.JSON(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_source_imports'))
    )
    with op.batch_alter_table('data_source_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_source_imports_dataset'), ['dataset'], unique=False)

    op.create_table('scoring_configs',
    sa.Column('config_version', sa.String(length=32), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('owner_household_weight', sa.Float(), nullable=False),
    sa.Column('age_45_plus_weight', sa.Float(), nullable=False),
    sa.Column('housing_age_weight', sa.Float(), nullable=False),
    sa.Column('income_weight', sa.Float(), nullable=False),
    sa.Column('serviceability_weight', sa.Float(), nullable=False),
    sa.Column('small_target_min', sa.Float(), nullable=False),
    sa.Column('small_target_max', sa.Float(), nullable=False),
    sa.Column('standard_target_min', sa.Float(), nullable=False),
    sa.Column('standard_target_max', sa.Float(), nullable=False),
    sa.Column('large_target_min', sa.Float(), nullable=False),
    sa.Column('large_target_max', sa.Float(), nullable=False),
    sa.Column('full_config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('config_version', name=op.f('pk_scoring_configs'))
    )
    op.create_table('territories',
    sa.Column('territory_id', sa.String(length=16), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_business_name', sa.String(length=200), nullable=False),
    sa.Column('starting_zip', sa.String(length=5), nullable=False),
    sa.Column('territory_size_class', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reservation_date', sa.Date(), nullable=True),
    sa.Column('reservation_expires_at', sa.Date(), nullable=True),
    sa.Column('reservation_extensions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('contract_start_date', sa.Date(), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('exceptions_json', sa.JSON(), nullable=True),
    sa.Column('generation_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('PROPOSED', 'RESERVED', 'ACTIVE_PROTECTED', 'PENDING_RELEASE', 'RELEASED', 'CANCELLED')", name=op.f('ck_territories_status_valid')),
    sa.CheckConstraint("territory_size_class IN ('SMALL', 'STANDARD', 'LARGE')", name=op.f('ck_territories_size_class_valid')),
    sa.PrimaryKeyConstraint('territory_id', name=op.f('pk_territories'))
    )
    with op.batch_alter_table('territories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_territories_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_territories_status'), ['status'], unique=False)

    op.create_table('data_field_provenance',
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=False),
    sa.Column('vintage', sa.String(length=16), nullable=False),
    sa.Column('table_id', sa.String(length=16), nullable=True),
    sa.Column('variables_json', sa.JSON(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['data_source_imports.id'], name=op.f('fk_data_field_provenance_import_id_data_source_imports')),
    sa.PrimaryKeyConstraint('field_name', name=op.f('pk_data_field_provenance'))
    )
    op.create_table('territory_zip_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('territory_id', sa.String(length=16), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('zip', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('date_assigned', sa.Date(), nullable=False),
    sa.Column('date_released', sa.Date(), nullable=True),
    sa.CheckConstraint("status IN ('RESERVED', 'ACTIVE_PROTECTED', 'PENDING_RELEASE', 'RELEASED')", name=op.f('ck_territory_zip_assignments_status_valid')),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.territory_id'], name=op.f('fk_territory_zip_assignments_territory_id_territories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_territory_zip_assignments'))
    )
    with op.batch_alter_table('territory_zip_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_territory_zip_assignments_territory_id'), ['territory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_territory_zip_assignments_zip'), ['zip'], unique=False)
        batch_op.create_index('uq_active_zip', ['zip'], unique=True, sqlite_where=sa.text("status IN ('RESERVED', 'ACTIVE_PROTECTED', 'PENDING_RELEASE')"), postgresql_where=sa.text("status IN ('RESERVED', 'ACTIVE_PROTECTED', 'PENDING_RELEASE')"))

    op.create_table('zcta_markets',
    sa.Column('zcta', sa.String(length=5), nullable=False),
    sa.Column('postal_zip', sa.String(length=5), nullable=True),
    sa.Column('primary_city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('state_fips', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('land_area_sq_miles', sa.Float(), nullable=True),
    sa.Column('water_area_sq_miles', sa.Float(), nullable=True),
    sa.Column('geometry_geojson', sa.Text(), nullable=True),
    sa.Column('total_population', sa.Integer(), nullable=True),
    sa.Column('total_households', sa.Integer(), nullable=True),
    sa.Column('owner_occupied_households', sa.Integer(), nullable=True),
    sa.Column('renter_occupied_households', sa.Integer(), nullable=True),
    sa.Column('owner_occupancy_percent', sa.Float(), nullable=True),
    sa.Column('owner_households_age_45_plus', sa.Integer(), nullable=True),
    sa.Column('owner_households_age_55_plus', sa.Integer(), nullable=True),
    sa.Column('owner_households_age_65_plus', sa.Integer(), nullable=True),
    sa.Column('total_housing_units', sa.Integer(), nullable=True),
    sa.Column('homes_built_before_2000', sa.Integer(), nullable=True),
    sa.Column('homes_built_before_1990', sa.Integer(), nullable=True),
    sa.Column('homes_built_before_1980', sa.Integer(), nullable=True),
    sa.Column('median_household_income', sa.Integer(), nullable=True),
    sa.Column('median_home_value', sa.Integer(), nullable=True),
    sa.Column('households_per_sq_mile', sa.Float(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('market_tier', sa.String(length=1), nullable=True),
    sa.Column('opportunity_units', sa.Float(), nullable=True),
    sa.Column('score_config_version', sa.String(length=32), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unserviceable_land_area', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('demographics_import_id', sa.Integer(), nullable=True),
    sa.Column('geography_import_id', sa.Integer(), nullable=True),
    sa.Column('source_release', sa.String(length=64), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(zcta) = 5', name=op.f('ck_zcta_markets_zcta_five_digits')),
    sa.ForeignKeyConstraint(['demographics_import_id'], ['data_source_imports.id'], name=op.f('fk_zcta_markets_demographics_import_id_data_source_imports')),
    sa.ForeignKeyConstraint(['geography_import_id'], ['data_source_imports.id'], name=op.f('fk_zcta_markets_geography_import_id_data_source_imports')),
    sa.PrimaryKeyConstraint('zcta', name=op.f('pk_zcta_markets'))
    )
    with op.batch_alter_table('zcta_markets', schema=None) as batch_op:
        batch_op.create_index('ix_zcta_markets_city_state', ['primary_city', 'state'], unique=False)
        batch_op.create_index(batch_op.f('ix_zcta_markets_market_tier'), ['market_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_zcta_markets_state'), ['state'], unique=False)

    op.create_table('zcta_adjacency',
    sa.Column('zcta_a', sa.String(length=5), nullable=False),
    sa.Column('zcta_b', sa.String(length=5), nullable=False),
    sa.Column('shared_boundary_length_m', sa.Float(), nullable=True),
    sa.Column('geography_import_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('zcta_a < zcta_b', name=op.f('ck_zcta_adjacency_ordered_pair')),
    sa.ForeignKeyConstraint(['geography_import_id'], ['data_source_imports.id'], name=op.f('fk_zcta_adjacency_geography_import_id_data_source_imports')),
    sa.ForeignKeyConstraint(['zcta_a'], ['zcta_markets.zcta'], name=op.f('fk_zcta_adjacency_zcta_a_zcta_markets')),
    sa.ForeignKeyConstraint(['zcta_b'], ['zcta_markets.zcta'], name=op.f('fk_zcta_adjacency_zcta_b_zcta_markets')),
    sa.PrimaryKeyConstraint('zcta_a', 'zcta_b', name=op.f('pk_zcta_adjacency'))
    )
    with op.batch_alter_table('zcta_adjacency', schema=None) as batch_op:
        batch_op.create_index('ix_zcta_adjacency_zcta_b', ['zcta_b'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zcta_adjacency', schema=None) as batch_op:
        batch_op.drop_index('ix_zcta_adjacency_zcta_b')

    op.drop_table('zcta_adjacency')
    with op.batch_alter_table('zcta_markets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zcta_markets_state'))
        batch_op.drop_index(batch_op.f('ix_zcta_markets_market_tier'))
        batch_op.drop_index('ix_zcta_markets_city_state')

    op.drop_table('zcta_markets')
    with op.batch_alter_table('territory_zip_assignments', schema=None) as batch_op:
        batch_op.drop_index('uq_active_zip', sqlite_where=sa.text("status IN ('RESERVED', 'ACTIVE_PROTECTED', 'PENDING_RELEASE')"), postgresql_where=sa.text("status IN ('RESERVED', 'ACTIVE_PROTECTED', 'PENDING_RELEASE')"))
        batch_op.drop_index(batch_op.f('ix_territory_zip_assignments_zip'))
        batch_op.drop_index(batch_op.f('ix_territory_zip_assignments_territory_id'))

    op.drop_table('territory_zip_assignments')
    op.drop_table('data_field_provenance')
    with op.batch_alter_table('territories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_territories_status'))
        batch_op.drop_index(batch_op.f('ix_territories_client_id'))

    op.drop_table('territories')
    op.drop_table('scoring_configs')
    with op.batch_alter_table('data_source_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_source_imports_dataset'))

    op.drop_table('data_source_imports')
    # ### end Alembic commands ###
